namespace: sctmp-dev

helmCharts:
  - name: rabbitmq
    repo: https://charts.bitnami.com/bitnami
    releaseName: mqtt-broker
    version: 3.11.9
    valuesInline:
      plugins:
        - rabbitmq_management
        - rabbitmq_peer_discovery_k8s
        - rabbitmq_mqtt
        - rabbitmq_web_mqtt
        - rabbitmq_amqp1_0
